"""removing uniqueness constraint for phone number

Revision ID: 04c572af39db
Revises: 99a352ab5400
Create Date: 2017-05-31 17:06:03.741016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c572af39db'
down_revision = '99a352ab5400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'])
    # ### end Alembic commands ###
