"""adding in association:


Revision ID: 30cfa23fc798
Revises: 04c572af39db
Create Date: 2017-06-01 16:41:53.046871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cfa23fc798'
down_revision = '04c572af39db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('is_host', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('events_host_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'host_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_host_id_fkey', 'events', 'users', ['host_id'], ['id'])
    op.drop_table('association')
    # ### end Alembic commands ###
