"""adding in tickets resource and table

Revision ID: 56116e40b8e1
Revises: dff17cc465eb
Create Date: 2017-06-02 11:54:38.233991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56116e40b8e1'
down_revision = 'dff17cc465eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('is_host', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_host', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='association_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='association_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='association_pkey')
    )
    op.drop_table('tickets')
    # ### end Alembic commands ###
