"""removing images from events

Revision ID: 99a352ab5400
Revises: c71b8f362e1c
Create Date: 2017-05-31 11:08:44.615545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a352ab5400'
down_revision = 'c71b8f362e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('location_name', sa.Text(), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('sold_out', sa.Boolean(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
