"""updating events more

Revision ID: dff17cc465eb
Revises: 30cfa23fc798
Create Date: 2017-06-01 17:21:10.128574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff17cc465eb'
down_revision = '30cfa23fc798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('host_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['host_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'host_id')
    # ### end Alembic commands ###
